### ISSUE TITLE
Regular sampling and fast sampling not equivalent in unconditional generation

### ISSUE THREAD

**Issue by gzhu06** [lmnt-com/diffwave#27]
Hi, thank you so much for your implementation.

I trained one unconditional generator, the fast sampling makes sense during inference using default noise schedule, like this:
<img width="642" alt="Screen Shot 2022-05-02 at 8 34 15 PM" src="https://user-images.githubusercontent.com/16846862/166354905-9e582f1e-bb1a-46a4-bb3c-18e76603ae16.png">

However, when I set fast_sampling to False, still with the default noise schedule, I got this:
<img width="633" alt="Screen Shot 2022-05-02 at 8 35 20 PM" src="https://user-images.githubusercontent.com/16846862/166358101-37f2e96f-69ea-44c7-81d1-05e563d83426.png">

Is this normal? Thanks in advance.

Also is this setting correct? The maximum beta in two schedules are different here.
```
noise_schedule=np.linspace(1e-4, 0.05, 50).tolist()
inference_noise_schedule=[0.0001, 0.001, 0.01, 0.05, 0.2, 0.5]
```

**Comment by sharvil** [comment]
It's unusual to get such a bad waveform when using `fast_sampling=False`, especially when it looks reasonable when fast sampling is enabled. I personally haven't trained an unconditional generator so I'm not sure if this issue is widespread or specific to your scenario. Maybe @Andrechang has some pointers -- they added the unconditional synthesis implementation to this repository.

The noise settings you listed look correct to me, and the maximum betas are expected to be significantly different.

**Comment by Andrechang** [comment]
It was quite sometime ago, but from what I recall, the unconditional generator wasn't good with fast_sampling=False
I didn't change the default params.py other than batch_size to fit in gpu memory

**Comment by gzhu06** [comment]
I see, but this is quite weird to me, because based on their [paper](https://arxiv.org/pdf/2106.00132.pdf), fast sampling is an approximation of the original version. Maybe increasing sampling steps and changing noise schedule could help?

**Comment by Andrechang** [comment]
I think it is worth a try to change sampling steps and changing noise schedules to see if it improves
