### ISSUE TITLE
Class-conditional waveform generation on the SC09 dataset

### ISSUE THREAD

**Issue by YIN95** [lmnt-com/diffwave#29]
Hi, 

I was wondering how the class-conditional generation is implemented. 

Thanks!

**Comment by sharvil** [comment]
Class-conditional generation hasn't been implemented in this codebase.

It should be quite straightforward to modify the code to support it since the architecture change is quite small (see Sec 3.2 / Global Conditioner). Instead of conditioning on a mel spectrogram, you'd just use an `nn.Embedding` layer to map a discrete label to a 128-dim vector, and expand it across the time dimension to match the target signal.
